vich_uploader:
    db_driver: orm

    mappings:
        profilePictures:
            uri_prefix: /userImages/profilePicture
            upload_destination: '%kernel.project_dir%/public/userImages/profilePicture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
